/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.NhanVien;
import Model.ThucUong;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ThucUongView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ThucUongView.class.getName());
    DefaultTableModel model;
    DefaultTableModel model2;

    /**
     * Creates new form ThucUongView
     */
    public ThucUongView() {
        initComponents();
        String header[] = {"Mã thức uống", "Tên gọi", "Giá tiền", "Ghi chú"};
        model = new DefaultTableModel(null, header);
        String header2[] = {"Mã Nhân Viên", "Tên Nhân Viên", "Quê Quán", "Lương", "Năm Sinh"};
        model2 = new DefaultTableModel(null, header2);
        tblTU.setModel(model);
        tblNV.setModel(model2);
    }

    public void loadDataToTable(List<ThucUong> list) {
        model.setRowCount(0);
        for (ThucUong item : list) {
            model.addRow(new Object[]{
                item.getMaTu(),
                item.getTenGoi(),
                item.getGia(),
                item.getGhiChu()
            });
        }
    }

    public ThucUong thucUongDuocChonTrongBang() {
        int index = tblTU.getSelectedRow();

        if (index == -1) {
            return null;
        }

        Object maValue = tblTU.getValueAt(index, 0);
        int maTU = (int) Double.parseDouble(maValue.toString());

        String tenGoi = tblTU.getValueAt(index, 1).toString();
        double giaTien = Double.parseDouble(
                tblTU.getValueAt(index, 2).toString()
        );
        String ghiChu = tblTU.getValueAt(index, 3).toString();

        return new ThucUong(maTU, tenGoi, giaTien, ghiChu);
    }

    public int thucUongDuocChon() {
        int index = tblTU.getSelectedRow();
        return index;
    }

    public void hienThiTU(ThucUong nv) {
        txtMa.setText(nv.getMaTu() + "");
        txtTen.setText(nv.getTenGoi());
        txtGia.setText(nv.getGia() + "");
        txtGhi.setText(nv.getGhiChu());
    }

    public void loadNVDataToTable(List<NhanVien> list) {
        model2.setRowCount(0);
        for (NhanVien item : list) {
            model2.addRow(new Object[]{
                item.getMaNV(),
                item.getHotenNv(),
                item.getQueQuanNV(),
                item.getLuongNV(),
                item.getNamSinhNV()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGhi = new javax.swing.JTextField();
        btnSua1 = new javax.swing.JButton();
        btnThem1 = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        sp = new javax.swing.JScrollPane();
        tblTU = new javax.swing.JTable();
        sp1 = new javax.swing.JScrollPane();
        tblNV = new javax.swing.JTable();
        btnThem2 = new javax.swing.JButton();
        txtManv = new javax.swing.JTextField();
        txtTennv = new javax.swing.JTextField();
        txtQuenv = new javax.swing.JTextField();
        txtLuongnv = new javax.swing.JTextField();
        txtNamsinhnv = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã thức uống:");

        jLabel2.setText("Tên gọi:");

        txtTen.addActionListener(this::txtTenActionPerformed);

        jLabel3.setText("Giá tiền:");

        jLabel4.setText("Ghi chú:");

        btnSua1.setText("Sửa");
        btnSua1.addActionListener(this::btnSua1ActionPerformed);

        btnThem1.setText("Thêm");

        btnXoa.setText("Xóa");

        tblTU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sp.setViewportView(tblTU);

        tblNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        sp1.setViewportView(tblNV);

        btnThem2.setText("Thêm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGhi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSua1)
                            .addComponent(btnThem1)
                            .addComponent(btnXoa))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem2))
                    .addComponent(txtTennv, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuenv, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLuongnv, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamsinhnv, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem2)
                            .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuenv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLuongnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamsinhnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtGhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sp1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSua1ActionPerformed

    public void ButtonListenerThem(ActionListener listener) {
        btnThem1.addActionListener(listener);
    }

    public void ButtonListenerXoa(ActionListener listener) {
        btnXoa.addActionListener(listener);
    }

    public void ButtonListenerSua(ActionListener listener) {
        btnSua1.addActionListener(listener);
    }

    public void ButtonListenerThemNV(ActionListener listener) {
        btnThem2.addActionListener(listener);
    }

    public void addTableclickedLintenner(MouseListener listener) {
        tblTU.addMouseListener(listener);
    }

    public void DebugVoil(String s) {
        JOptionPane.showMessageDialog(this, s);
    }

    public boolean Confirm(String s) {
        int result = JOptionPane.showConfirmDialog(
                this,
                s,
                "Xác nhận",
                JOptionPane.YES_NO_OPTION
        );

        return result == JOptionPane.YES_OPTION;
    }
    
    
    

    public double getMa() {
        try {
            return Double.parseDouble(txtMa.getText().trim());
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(
                    "Mã thức uống phải là số hợp lệ!"
            );
        }
    }

    public String getName() {
        return txtTen.getText();
    }

    public String getGia() {
        return txtGia.getText();
    }

    public String getGhichu() {
        return txtGhi.getText();
    }

    public int getRow() {
        return tblTU.getSelectedRow();
    }

    public double getMaByRow(int row) {
        return Double.parseDouble(
                tblTU.getValueAt(row, 0).toString()
        );
    }

    public String getManv() {
        return txtManv.getText();
    }

    public String getTennv() {
        return txtTennv.getText();
    }

    public String getQuequannv() {
        return txtQuenv.getText();
    }

    public String getLuongnv() {
        return txtLuongnv.getText();
    }

    public String getnamsinhnv() {
        return txtNamsinhnv.getText();
    }

    public int getRowNV() {
        return tblNV.getSelectedRow();
    }

    //////////////////////////////////////////////////
    ///
    public void setManv(String s) {
        txtManv.setText(s);
    }

    public void setNamenv(String s) {
        txtTennv.setText(s);
    }

    public void setQuenv(String s) {
        txtQuenv.setText(s);
    }

    public void setLuongnv(String s) {
        txtLuongnv.setText(s);
    }

    public void setNamsv(String s) {
        txtNamsinhnv.setText(s);
    }

    ///
    public void setMa(String s) {
        txtMa.setText(s);
    }

    public void setName(String s) {
        txtTen.setText(s);
    }

    public void setgia(String s) {
        txtGia.setText(s);
    }

    public void setGhichu(String s) {
        txtGhi.setText(s);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ThucUongView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane sp;
    private javax.swing.JScrollPane sp1;
    private javax.swing.JTable tblNV;
    private javax.swing.JTable tblTU;
    private javax.swing.JTextField txtGhi;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtLuongnv;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtManv;
    private javax.swing.JTextField txtNamsinhnv;
    private javax.swing.JTextField txtQuenv;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTennv;
    // End of variables declaration//GEN-END:variables
}
